[package]
name = "ic-call-retry"
version = "0.1.0"
edition = "2021"

[features]
use_call_chaos = ["dep:ic-call-chaos"]

[dependencies]
ic-cdk = { workspace = true }
ic-call-chaos = { path = "../../call_chaos/call_chaos", optional = true }